### PR TITLE
added DT Mania PP

### PR DESCRIPTION
**Pull request by MarcPlaying**
A simple implementation of DT Mania PP,

### CODE REVIEW

**Comment by qewc** [comment]
Fuck you, asshole. This is unneeded.

**Comment by cmyui** [comment]
mfw no one knows the values

i think 1.75 was closer lol

i forget what we had before

**Comment by MarcPlaying** [comment]
Ilyt told me that are better values @cmyui

**Comment by qewc** [comment]
this is literally what they had before

**Pull request merged**
